### ISSUE TITLE
save_on_google_sheet waits infinitely for price/expense value from user

### ISSUE THREAD

**Issue by PartikIITD** [sickmz/microw#14]
User price input is not working. After entering the price, it does nothing. It seems it is waiting for user input infinitely even after entering the price value and pressing enter on the Android Telegram app. After entering the price, if we press any of the menu buttons, it actually takes the text value of those buttons and assigns it to update.message.text, which then leads to the ValueError. Because it is stuck at getting the update.message.text value, it doesn't save anything on the Gsheet.

**Comment by sickmz** [comment]
- Have you enabled the google sheet API in Google Cloud Platform?
- Have you created the service account on Google Cloud platform?
- Did you import the credentials into the project root?
- Have you shared your spreadsheet with the service account?
- Are you using the google sheet id in the `.env` file?

The problem is one of these, I don't have an Android phone but I downloaded Bluestack to try to replicate the issue and everything works as expected, so I exclude _(at this time)_ that it is a bug related to the code.

**Comment by PartikIITD** [comment]
I was directly entering the price value, and it wasn't working. I tried left-swiping the update.callback_query.message.edit_text("Enter the price for this item:") so as to reply to that particular statement, and it worked. Thanks.

**Comment by chiruleonard** [comment]
Same issue but mine didn't work with left-swipe

```
2024-05-20 21:49:44,258 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
Traceback (most recent call last):
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/spreadsheet.py", line 307, in worksheet
    item = finditem(
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/utils.py", line 168, in finditem
    return next(item for item in seq if func(item))
StopIteration

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1277, in process_update
    await coroutine
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_handlers/conversationhandler.py", line 857, in handle_update
    new_state: object = await handler.handle_update(
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
    return await self.callback(update, context)
  File "/home/iancului27/scripts/microw/microw.py", line 95, in save_on_google_sheet
    ws = get_worksheet(SPREADSHEET_ID, EXPENSE_SHEET)
  File "/home/iancului27/scripts/microw/microw.py", line 54, in get_worksheet
    cache[key] = gc.open_by_key(spreadsheet_id).worksheet(worksheet_name)
  File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/spreadsheet.py", line 313, in worksheet
    raise WorksheetNotFound(title)
gspread.exceptions.WorksheetNotFound: Expenses
```
The worksheet name is correct setup.

**Comment by sickmz** [comment]
> Same issue but mine didn't work with left-swipe
> 
> ```
> 2024-05-20 21:49:44,258 - telegram.ext.Application - ERROR - No error handlers are registered, logging exception.
> Traceback (most recent call last):
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/spreadsheet.py", line 307, in worksheet
>     item = finditem(
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/utils.py", line 168, in finditem
>     return next(item for item in seq if func(item))
> StopIteration
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_application.py", line 1277, in process_update
>     await coroutine
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_handlers/conversationhandler.py", line 857, in handle_update
>     new_state: object = await handler.handle_update(
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/telegram/ext/_handlers/basehandler.py", line 157, in handle_update
>     return await self.callback(update, context)
>   File "/home/iancului27/scripts/microw/microw.py", line 95, in save_on_google_sheet
>     ws = get_worksheet(SPREADSHEET_ID, EXPENSE_SHEET)
>   File "/home/iancului27/scripts/microw/microw.py", line 54, in get_worksheet
>     cache[key] = gc.open_by_key(spreadsheet_id).worksheet(worksheet_name)
>   File "/home/iancului27/scripts/microw/venv/lib/python3.10/site-packages/gspread/spreadsheet.py", line 313, in worksheet
>     raise WorksheetNotFound(title)
> gspread.exceptions.WorksheetNotFound: Expenses
> ```
> 
> The worksheet name is correct setup.

This is a `gspread` exception, look [this](https://docs.gspread.org/en/latest/api/exceptions.html). 

Try to debug by printing `print()` of the variables in `.env` to check if you are loading them correctly or try passing the name of the worksheet without from the `.env` file.  You can also try accessing your want via index with `worksheet = sh.get_worksheet(0)`.

You definitely have a configuration problem. If you can't solve it, try writing to me on [telegram](https://t.me/sickmz).
